# Generated by Django 5.2.17 on 2026-09-17 21:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(unique=True)),
                ('capacite', models.PositiveSmallIntegerField()),
                ('statut', models.CharField(choices=[('libre', 'Libre'), ('occupee', 'Occupée'), ('inactive', 'Inactive')], default='libre', max_length=20)),
            ],
            options={
                'db_table': 'table_restaurant',
            },
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code_unique', models.CharField(max_length=64, unique=True)),
                ('url_destination', models.URLField(max_length=500)),
                ('date_generation', models.DateTimeField(auto_now_add=True)),
                ('statut', models.CharField(choices=[('actif', 'Actif'), ('expire', 'Expiré'), ('desactive', 'Désactivé')], default='actif', max_length=20)),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qrcodes', to='tables.table')),
            ],
            options={
                'db_table': 'qrcode',
            },
        ),
    ]
