# Generated by Django 5.2.17 on 2026-09-20 19:49

import django.db.models.deletion
import services.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nom', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('prix', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('disponible', models.BooleanField(default=True)),
                ('restaurant', models.ForeignKey(default=services.models._restaurant_par_defaut, on_delete=django.db.models.deletion.PROTECT, related_name='services', to='restaurant.restaurant')),
            ],
            options={
                'db_table': 'service',
                'ordering': ['nom'],
            },
        ),
    ]
